# Generated by Django 2.0.5 on 2018-05-18 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_regis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('traval_start_date', models.DateTimeField()),
                ('traval_end_date', models.DateTimeField()),
                ('trip_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='login_regis.User')),
            ],
        ),
    ]
