# Generated by Django 2.0.5 on 2018-05-18 17:42

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('login_regis', '0002_trip'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='trip',
            managers=[
                ('obj', django.db.models.manager.Manager()),
            ],
        ),
    ]
