# Generated by Django 2.0.5 on 2018-05-18 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_regis', '0003_auto_20180518_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='users_joined',
            field=models.ManyToManyField(related_name='users_joining', to='login_regis.User'),
        ),
    ]
